name: Build/Release Electron App
on: 
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggers

defaults:
  run:
    working-directory: ./Lacework-Compliance-Reporter

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Lacework-Compliance-Reporter/electron/package-lock.json
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate  # On Windows: venv\Scripts\activate
          pip install -r requirements.txt
          
      - name: Install Electron dependencies
        working-directory: ./Lacework-Compliance-Reporter/electron
        run: npm ci
        
      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          package_root: ./Lacework-Compliance-Reporter/electron
          working-directory: ./Lacework-Compliance-Reporter
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          args: --publish=never 
